### PR TITLE
Update setting.py

### PR DESCRIPTION
**Pull request by rhendre**
To solve the error

### CODE REVIEW

**Comment by anguloa** [comment]
Do I have to approve this somehow?

A.A.
(Mobile)

**Comment by rhendre** [comment]
No I got the change in, just have to restart the server to check. Did a
similar thing happen earlier?

**Comment by anguloa** [comment]
We’ve had to restart the server in the past, but the current error message on the site is new-

A.A.
(Mobile)

**Comment by rhendre** [comment]
When I put in the restart command it’s expecting a job name. Do you know
which job name should I use?

**Pull request merged**
